### ISSUE TITLE
some comments on Stan cheat sheet

### ISSUE THREAD

**Issue by bob-carpenter** [sieste/STAN_cheatsheet#1]
This is great.  I have a few suggestions.

* "STAN" -> "Stan"  (it's not an acronym)

* new local variable definitions can be within curly braces within a block

* it's not lines that need to end in semicolons, it's atomic statements (like assignment and sampling statements)

* `increment_log_prob(lp)` has been deprecated and replaced with `target += lp`

* `normal_log(y, mu, sigma)` has been deprecated and replaced with `normal_lpdf(y | mu, sigma)`

* the `_lpdf` and `_lpmf` (for discrete mass functions) are not quite the same as sampling statements because the sampling statements are clever enough to drop constants that don't depend on any parameters

* it might help to separate the Stan modeling sheet from the RStan sheet or at least clearly indicate which is which (e.g., compile model is in RStan)

* we like to use "draw" for a single draw and "sample" for a set of draws.  So that'd be either "draws" or "sample" (or "fit") rather than "sampls"

* setting the seed in R doesn't affect what happens in Stan if the seed is supplied for Stan;  it will affect R generation, of course

* cool!  I didn't realize you could specify the cores argument for the call to `stan`

* what you are calling diagnostics are what we would call summary statistics and visualizations;  the diagnostics are important and include things like divergences, tree depth, BFMI, etc.

* "extracting samples" -> "extracting draws"  (the latest version of our manual cleans up the last vestiges of the old language)

* log_lik could also be computed as a transformed parameter if you can use it in the model;  usually it's more efficient to vectorize the model and recompute `log_lik` in the generated quantities block (where the `log_lik` is a vector (array)? of log likelihoods, one for each data item).

* you can sample from the prior by setting data size equal to zero (then the likelihood drops out);  in you rexample, that would have `x` be size 0.

* you might want to direct people to our recommended priors page: https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations

P.S. I found this because https://github.com/dimitry12 linked from one of our issues on stan-dev: 
https://github.com/stan-dev/propaganda/issues/1#issuecomment-346509415

P.P.S.  I'll see if you respond to this issue and then post a link on our message boards.  Thanks for creating it.

**Comment by sieste** [comment]
Thanks for the helpful comments, Bob. I hope the cheat sheet is now up to date.

**Comment by bob-carpenter** [comment]
Looks good.  Thanks for updating.
